In [1]:
#!pip install imgaug
#!pip install torch_snippets
!pip install lxml
from lxml.etree import Element, SubElement, tostring
import pprint
from xml.dom.minidom import parseString

import PIL
from matplotlib import pyplot as plt
from PIL import Image
from torch_snippets import show, Glob, np, choose
import array
import cv2
import matplotlib.image as mpim
import imgaug as ia
import imgaug.augmenters as iaa
from imgaug.augmentables.bbs import BoundingBox, BoundingBoxesOnImage
import numpy as np
import glob
import random
%cd C:\Users\Hp\Desktop\one_shot_omr\lib
%load_ext autoreload 
%autoreload 2
from generate_images import *
from test_images import *

2021-07-29 10:12:55.746 | WARNING  | torch_snippets:<module>:8 - torch is not found. Skipping relevant imports from submodule `torch_loader`
Exception: No module named 'torch'
2021-07-29 10:12:57.029 | WARNING  | torch_snippets:<module>:13 - sklearn is not found. Skipping relevant imports from submodule `sklegos`
Exception: No module named 'sklego'


C:\Users\Hp\Desktop\one_shot_omr\lib


2021-07-29 10:12:57.852 | INFO     | generate_images:<module>:27 - 1870 files found at C:\Users\Hp\/dataset1/dataset/YES/*
2021-07-29 10:12:57.904 | INFO     | generate_images:<module>:28 - 3715 files found at C:\Users\Hp\/dataset1/dataset/NO/*
2021-07-29 10:12:57.916 | INFO     | generate_images:<module>:27 - 1870 files found at C:\Users\Hp\/dataset1/dataset/YES/*
2021-07-29 10:12:57.938 | INFO     | generate_images:<module>:28 - 3715 files found at C:\Users\Hp\/dataset1/dataset/NO/*


In [2]:
root="C:\\Users\\Hp\\"
ia.seed(1)
#C:/Users/Hp/dataset1/dataset/Internet access_4.png
val=input("Template Image path: ")
IMAGE = cv2.imread(val)
#2
checkbox=int(input("Number of Checkboxes: "))

BBS = BoundingBoxesOnImage([
        BoundingBox(x1=15, y1=35, x2=30, y2=52),
        BoundingBox(x1=86, y1=35, x2=102, y2=52)
    ], shape=IMAGE.shape
)
#C:/Users/Hp/dataset1/test_new1/
loc=input("Saving of Images path: ")
#10
no_of_images=int(input("No. of images you want to generate: "))
#generate_images_yolo(IMAGE,BBS,loc,no_of_images)
generate_images_icevision(IMAGE,BBS,loc,no_of_images)

Template Image path: C:/Users/Hp/dataset1/dataset/Internet access_4.png
Number of Checkboxes: 2
Saving of Images path: C:/Users/Hp/dataset1/test_new1/
No. of images you want to generate: 2


In [3]:
root="C:\\Users\\Hp\\"
# Load Yolo
#C:/Users/Hp/optum_test/test_final_2_Internet axis/yolov3_custom_4000.weights
weight=input("Weights File Location: ")
#C:/Users/Hp/optum_test/test_final_2_Internet axis/yolov3_custom.cfg
custom_file=input("Custom File Location: ")
net = cv2.dnn.readNet(weight,custom_file)

# Name custom object
classes = ["YES1","NO1","YES2","NO2"]

# Images path
#C:/Users/Hp/dataset1/test_new1/*.png
results_path=input("Location for saving of Prediction: ")
images_path = glob.glob(results_path)
test(classes,images_path,net)

Weights File Location: C:/Users/Hp/optum_test/test_final_2_Internet axis/yolov3_custom_4000.weights
Custom File Location: C:/Users/Hp/optum_test/test_final_2_Internet axis/yolov3_custom.cfg
Location for saving of Prediction: C:/Users/Hp/dataset1/test_new1/*.png
1
1
3
3
[[0]
 [2]]
0
3
[[1]
 [0]]
1
1
3
3
[[2]
 [0]]
1
1
1
3
3
[[1]
 [4]]
1
1
3
[[2]
 [1]]
0
2
[[1]
 [0]]
1
1
2
2
[[2]
 [1]]
1
1
3
[[2]
 [0]]
1
2
[[1]
 [0]]
0
2
[[1]
 [0]]


In [15]:
ia.seed(1)
yes_checkbox_paths=[""]*2
no_checkbox_paths=[""]*2

root="C:\\Users\\Hp\\"
j=0
all_path={}
for i in range(2):
    yes_checkbox_paths[i] = Glob(f"{root}/dataset1/dataset/YES/*")
    no_checkbox_paths[i] = Glob(f"{root}/dataset1/dataset/NO/*")
#yes1_checkbox_paths = Glob(f"{root}/dataset1/dataset/YES/*")
#no1_checkbox_paths = Glob(f"{root}/dataset1/dataset/NO/*")

    all_paths[i+j]=yes_checkbox_paths[i]
    all_paths[i+j+1]=no_checkbox_paths[i]
    
    
    j+=1
print(all_paths.keys())
    

2021-07-22 16:12:15.150 | INFO     | __main__:<module>:9 - 1870 files found at C:\Users\Hp\/dataset1/dataset/YES/*
2021-07-22 16:12:15.228 | INFO     | __main__:<module>:10 - 3715 files found at C:\Users\Hp\/dataset1/dataset/NO/*
2021-07-22 16:12:15.261 | INFO     | __main__:<module>:9 - 1870 files found at C:\Users\Hp\/dataset1/dataset/YES/*
2021-07-22 16:12:15.334 | INFO     | __main__:<module>:10 - 3715 files found at C:\Users\Hp\/dataset1/dataset/NO/*


dict_keys([2, 3, 0, 1])


In [7]:
root="C:\\Users\\Hp\\"

yes_checkbox_paths = Glob(f"{root}/dataset1/dataset/YES/*")
no_checkbox_paths = Glob(f"{root}/dataset1/dataset/NO/*")
yes1_checkbox_paths = Glob(f"{root}/dataset1/dataset/YES/*")
no1_checkbox_paths = Glob(f"{root}/dataset1/dataset/NO/*")

all_paths = {
    0:yes_checkbox_paths,
    1:no_checkbox_paths,
    2:yes1_checkbox_paths,
    3:no1_checkbox_paths
}
print(all_paths)


2021-07-22 14:04:02.210 | INFO     | __main__:<module>:3 - 1870 files found at C:\Users\Hp\/dataset1/dataset/YES/*
2021-07-22 14:04:02.233 | INFO     | __main__:<module>:4 - 3715 files found at C:\Users\Hp\/dataset1/dataset/NO/*
2021-07-22 14:04:02.249 | INFO     | __main__:<module>:5 - 1870 files found at C:\Users\Hp\/dataset1/dataset/YES/*
2021-07-22 14:04:02.271 | INFO     | __main__:<module>:6 - 3715 files found at C:\Users\Hp\/dataset1/dataset/NO/*


{0: ['C:\\Users\\Hp\\/dataset1/dataset/YES\\0.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1004.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1005.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1007.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1011.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1016.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1019.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1024.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1026.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1031.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1037.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1039.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1043.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1045.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1050.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1051.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1053.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1055.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1059.png', 'C:\\Users\\Hp\\/dataset1/dataset/YES\\1063.png'

In [ ]:
root="C:\\Users\\Hp\\"
ia.seed(1)
IMAGE = cv2.imread(f"{root}/dataset1/dataset/Internet access_4.png")
BBS = BoundingBoxesOnImage([
        BoundingBox(x1=15, y1=35, x2=30, y2=52),
        BoundingBox(x1=86, y1=35, x2=102, y2=52)
    ], shape=IMAGE.shape
)
generate_images(IMAGE,BBS,f'{root}/dataset1/test_new1/',5)

In [ ]:
root="C:\\Users\\Hp\\"
# Load Yolo
net = cv2.dnn.readNet(f"{root}/optum_test/test_final_2_Internet axis/yolov3_custom_4000.weights",f"{root}/optum_test/test_final_2_Internet axis/yolov3_custom.cfg")

# Name custom object
classes = ["YES1","NO1","YES2","NO2"]

# Images path
images_path = glob.glob(f"{root}/dataset1/test_new1/*.png")
test(classes,images_path,net)